#pragma once
#include "disp.h"
#include "board.h"
#include "reg.h"
#include "lan.h"

class Window
{

public:

    const long launchw = 320;
    const long launchh = 368;
    const long titlew = 256;
    const long titleh = 256;
    const long menuw = 24;
    const long menuh = 24;
    const long facew = 24;
    const long faceh = 24;
    const long iconw = 16;
    const long iconh = 16;
    const long digtw[3] = {13, 9, 13};
    const long digth[3] = {24, 17, 24};
    const long okw = 144;
    const long okh = 36;
    const long btnw = 36;
    const long btnh = 36;
    const long tutw = 120;
    const long tuth = 36;
    const long aboutw = 360;
    const long abouth = 240;
    const long helpw = 640;
    const long helph = 480;
    const long fontth = 64;
    const long fontfh = 32;
    const long fonth = 24;
    const long fontsh = 17;
    const long fontmh = 13;
    const long okh_ = abouth - (fontth + fonth * 4);
    const long cursorw = 12;
    const long cursorh = 19;
    const long clickw = 48;
    const long clickh = 72;
    const long arroww = 24;
    const long arrowh = 24;

    pbitmap ptitle_ = NULL;
    pbitmap pbg_ = NULL;
    pbitmap pmenu_ = NULL;
    pbitmap pmenu1[2] = {NULL, NULL};
    pbitmap pmenu2[2] = {NULL, NULL};
    pbitmap pmenu3[2] = {NULL, NULL};
    pbitmap pmenuq[2] = {NULL, NULL};
    pbitmap pmenua[2] = {NULL, NULL};
    pbitmap pmenus[2] = {NULL, NULL};
    pbitmap pmenum[2] = {NULL, NULL};
    pbitmap pmenut[2] = {NULL, NULL};
    pbitmap pmenud[2] = {NULL, NULL};
    pbitmap pmenun[2] = {NULL, NULL};
    pbitmap pmenug[7][2] = {{NULL, NULL}, {NULL, NULL}, {NULL, NULL}, {NULL, NULL}, {NULL, NULL}, {NULL, NULL}, {NULL, NULL}};
    pbitmap pface_ = NULL;
    pbitmap pface[9] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
    pbitmap picon_ = NULL;
    pbitmap picon[11] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
    pbitmap piconc = NULL;
    pbitmap piconq = NULL;
    pbitmap piconf = NULL;
    pbitmap piconm = NULL;
    pbitmap picone = NULL;
    pbitmap piconn = NULL;
    pbitmap piconp = NULL;
    pbitmap picona = NULL;
    pbitmap piconu = NULL;
    pbitmap pdigt_[3] = {NULL, NULL, NULL};
    pbitmap pdigt[10][3] = {{NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}, {NULL, NULL, NULL}};
    pbitmap pdigtmin[3] = {NULL, NULL, NULL};
    pbitmap pdigtnul[3] = {NULL, NULL, NULL};
    pbitmap pok_ = NULL;
    pbitmap pok = NULL;
    pbitmap pbtn = NULL;
    pbitmap pcursor_ = NULL;
    pbitmap pcursor = NULL;
    pbitmap pclick_ = NULL;
    pbitmap pclickl = NULL;
    pbitmap pclickr = NULL;
    pbitmap pclickn = NULL;
    pbitmap pclicka = NULL;
    pbitmap parrow_ = NULL;
    pbitmap parrowl = NULL;
    pbitmap parrowr = NULL;
    pbitmap parrowu = NULL;
    pbitmap parrowd = NULL;
    pbitmap parrowm = NULL;
    pbitmap parrowp = NULL;

    const long transparent = 0x000001;

    long color[9] = {0xc0c0c0, 0xAFAFAF, 0x010101, 0xc0c0c0, 0x0000ff, 0xff0000, 0x008000, 0x808080, 0xc0c0c0};
    long colori = 0;
    long cfg;
    long cbg;
    long ctfg;
    long ctbg;
    long cred;
    long cblue;
    long cgreen;
    long cline;
    long cmine;
    long transparent_ = 0xAFAFAF;

    bool isbmp = false;

    Reg reg;
    HICON hicon_res;
    HICON hicon_file;
    HICON hicon;
    Board bd;
    Block bl;
    const long maxhelp = 6;
    long helpi = 0;
    bool helpb = true;
    bool cheatb = false;
    bool waitb = false;
    pbitmap pwin = NULL;
    pbitmap pwint = NULL;
    const long minh = 600;
    const long minw = 800;
    long mult_ = 0;
    double mult = 1;
    WINDOWPLACEMENT wn;
    bool showmax = false;
    bool showmax_ = false;
    long w_ = 0;
    long h_ = 0;
    long x_ = 0;
    long y_ = 0;
    RECT rect;
    long xscr = 0;
    long yscr = 0;
    long wscr = 0;
    long hscr = 0;
    bool barb = true;
    long md = 0;
    bool ml = false;
    bool mr = false;
    long mx = -1;
    long my = -1;
    bool mi = false;
    long lead_5 = 0;
    bool singleb = false;
    long boardb = 0;
    double timerefresh = 0;

    CRITICAL_SECTION cs;

    Window();
    ~Window();
    void loadsettingcloud();
    void savesettingcloud();
    void loadsetting();
    void savesetting();
    void loadboardcloud();
    void saveboardcloud();
    void loadboard();
    void saveboard();
    void initmult();
    void loadicon();
    void loadallpaint();
    void loadall();
    void initwindow();
    void releasewindow();
    void initwindow(bool b);
    void initcolor();
    void initbmp();
    void paintmenu();
    void paintface();
    void paintnumber(long n, long l, long x, long y, long w, long h, long b);
    void paintnumber(long n, long l, long x, long y, long b);
    void paintnumber(long n, long l, long x, long y);
    void paintlevel();
    void paintblock(Block &b, long i, long j, long x, long y, long w, long h);
    void paintboard(Block &b, long x, long y);
    void paintboard(Block &b, long x, long y, long cx, long cy);
    void paintboard();
    void paintline(pbitmap p, long n, long x, long y);
    void paintline(pbitmap pa, pbitmap pb, long a, long b, long x, long y);
    void paintline(pbitmap pa, pbitmap pb, pbitmap pc, long a, long b, long c, long x, long y);
    void paintline(pbitmap pa, pbitmap pb, pbitmap pc, pbitmap pd, long a, long b, long c, long d, long x, long y);
    void paintline(pbitmap pa, pbitmap pb, pbitmap pc, pbitmap pd, pbitmap pe, long a, long b, long c, long d, long e, long x, long y);
    void painthelp();
    void painttut();
    void painttitle(long load);
    void paintevent(bool freshb);
    void paintevent();
    void paintrefresh();
    bool isin(long ex, long ey, long x, long y, long w, long h);
    void sethelp(long helpi_);
    void savescr();
    void switchskin();
    void switchskin(long colori_);
    void switchmd();
    void switchmd(long md_);
    void tutevent(long ex, long ey, bool tutkb);
    void mouseeventboard_(long ex_, long ey_, long eb_, long md_);
    void mouseeventboard(long ex_, long ey_, long eb_, long md_);
    void mouseevent(long ex_, long ey_, long eb_);
    void keyevent(long key);
    void doaction();

    void setfontname_(const char* s);
    void setfontheight_(unsigned long h);
    void setfontweight_(unsigned long wg);
    void drawtextxy_(pbitmap b,const short int* s,long x,long y,unsigned long w,unsigned long h,unsigned long cfg,unsigned long cbg,unsigned long format);
    void drawtextxy_(pbitmap b,const short int* s,long x,long y,unsigned long w,unsigned long h,unsigned long cfg,unsigned long cbg);
    void drawtextxy_(pbitmap b,const char* s,long x,long y,unsigned long w,unsigned long h,unsigned long cfg,unsigned long cbg);
    void drawtextxy_(pbitmap b,const char* s,long x,long y,unsigned long cfg,unsigned long cbg);
    unsigned long getstringwidth_(const char* s);

};
